// Generated by CoffeeScript 1.6.1

$(function() {
  $('.disabled').each(function() {
    return $(this).attr('tabindex', '-1');
  });
  $('body').on('click', '.disabled', function(e) {
    e.preventDefault();
    return false;
  });
});
