// Generated by CoffeeScript 1.6.1

$(function() {
  var delay, dropdown, menu, navitem;
  delay = '';
  navitem = $('nav > ul > li');
  navitem.find('>a').on({
    focus: function(e) {
      $('nav > ul > li').removeClass('on');
      return $('nav > ul > li > ul').hide();
    }
  });
  menu = $('nav > ul > li.menu');
  menu.on({
    mouseenter: function(e) {
      if ($(window).width() > 768) {
        clearTimeout(delay);
        $('nav > ul > li').removeClass('on');
        $('nav > ul > li > ul').hide();
        return $(this).addClass('on');
      }
    },
    mouseleave: function(e) {
      if ($(window).width() > 768) {
        return delay = setTimeout((function() {
          $('nav > ul > li').removeClass('on');
          return $('nav > ul > li > ul').hide();
        }), 350);
      }
    },
    click: function(e) {
      var $this;
      if ($(window).width() < 768) {
        if ($(e.target).parent('li.menu').size() > 0) {
          $this = $(this);
          $(this).children('ul').slideToggle(300, function() {
            return $this.toggleClass('on');
          });
          e.preventDefault();
          return false;
        }
      }
    },
    tap: function(e) {
      var $this;
      if ($(e.target).parent('li.menu').size() > 0) {
        $this = $(this);
        $(this).children('ul').slideToggle(300, function() {
          return $this.toggleClass('on');
        });
        e.preventDefault();
        return false;
      }
    }
  });
  menu.find('>a').on({
    focus: function() {
      return $(this).parent('li.menu').trigger('mouseenter');
    }
  });
  menu.find('li:last-child > a').on({
    blur: function() {
      return $(this).closest('li.menu').trigger('mouseleave');
    }
  });
  dropdown = $('.dropdown');
  dropdown.on({
    focus: function() {
      return $(this).addClass('on');
    }
  });
  dropdown.find('li:last-child a').on({
    blur: function() {
      return dropdown.filter('.on').removeClass('on');
    }
  });
  $('body').on('click', function(e) {
    if ($(e.target).hasClass('dropdown')) {
      $(e.target).toggleClass('on');
    } else {
      if (dropdown.filter('.on').length) {
        dropdown.filter('.on').removeClass('on');
      }
    }
    if (navitem.filter('.menu.on').length) {
      return navitem.filter('.menu.on').removeClass('on');
    }
  });
});
