// Generated by CoffeeScript 1.6.1
/*
 * Requires jquery.responsiveText.js
*/

$(function() {
  return $('.responsive').not('table').each(function(index, object) {
    var compression, max, min;
    compression = 10;
    min = 10;
    max = 200;
    compression = parseFloat($(this).attr('data-compression') || compression);
    min = parseFloat($(this).attr('data-min') || min);
    max = parseFloat($(this).attr('data-max') || max);
    $(object).responsiveText({
      compressor: compression,
      minSize: min,
      maxSize: max
    });
    return $(this).hover((function() {
      var difference;
      console.log($(this));
      difference = $this.get(0).scrollWidth - $this.width();
      if (difference > 0) {
        return $this.stop().animate({
          "text-indent": -difference
        }, settings.scrollTime);
      }
    }), function() {
      return $this.stop().animate({
        "text-indent": 0
      }, settings.scrollBackTime);
    });
  });
});
