// Generated by CoffeeScript 1.6.1

$(function() {
  return $('body').on('click', '.tabs > ul > li > a[href^=#]', function(e) {
    var tabs;
    if (!$(this).hasClass('disabled')) {
      tabs = $(this).parents('.tabs');
      tabs.find('> ul li a').removeClass('active');
      $(this).addClass('active');
      tabs.children('div').removeClass('active');
      tabs.children($(this).attr('href')).addClass('active');
    }
    e.preventDefault();
    return false;
  });
});
