// Generated by CoffeeScript 1.6.1

$(function() {
  return $('body').on('click', '.tiles > .tile', function(e) {
    var tiles;
    if (!$(this).hasClass('disabled')) {
      tiles = $(this).parents('.tiles');
      tiles.find('> .tile').removeClass('active');
      tiles.find('> input').val($(this).data('value'));
      $(this).addClass('active');
    }
    e.preventDefault();
    return false;
  });
});
